import { serve } from 'https://deno.land/std@0.168.0/http/server.ts';
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2.49.1';
import { corsHeaders } from '../_shared/cors.ts';
import { authenticateAdmin, isAuthError } from '../_shared/auth.ts';
import { successResponse, errorResponse } from '../_shared/response.ts';

interface RequestBody {
  prompt: string;
  eventId: string;
}

serve(async (req: Request) => {
  // Handle CORS preflight
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    // Authenticate admin
    const authResult = await authenticateAdmin(req);
    if (isAuthError(authResult)) {
      return errorResponse(authResult.error, authResult.status, 'UNAUTHORIZED');
    }

    // Parse request body
    const body: RequestBody = await req.json();
    const { prompt, eventId } = body;

    if (!prompt || !eventId) {
      return errorResponse('Missing prompt or eventId', 400, 'INVALID_PAYLOAD');
    }

    console.log(`Generating image for event ${eventId} with prompt: ${prompt.substring(0, 100)}...`);

    // Get Lovable API key
    const LOVABLE_API_KEY = Deno.env.get('LOVABLE_API_KEY');
    if (!LOVABLE_API_KEY) {
      console.error('LOVABLE_API_KEY not configured');
      return errorResponse('AI service not configured', 500, 'INTERNAL_ERROR');
    }

    // Call Lovable AI Gateway for image generation
    const aiResponse = await fetch('https://ai.gateway.lovable.dev/v1/chat/completions', {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${LOVABLE_API_KEY}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        model: 'google/gemini-3-pro-image-preview',
        messages: [{
          role: 'user',
          content: prompt
        }],
        modalities: ['image', 'text']
      })
    });

    if (!aiResponse.ok) {
      const errorText = await aiResponse.text();
      console.error(`AI Gateway error: ${aiResponse.status} - ${errorText}`);
      
      if (aiResponse.status === 429) {
        return errorResponse('Rate limit exceeded, please try again later', 429, 'RATE_LIMITED');
      }
      if (aiResponse.status === 402) {
        return errorResponse('AI credits exhausted, please add funds', 402, 'FORBIDDEN');
      }
      
      return errorResponse('AI image generation failed', 500, 'INTERNAL_ERROR');
    }

    const aiData = await aiResponse.json();
    console.log('AI response received:', JSON.stringify(aiData).substring(0, 200));

    // Extract image from response
    const imageUrl = aiData.choices?.[0]?.message?.images?.[0]?.image_url?.url;
    
    if (!imageUrl || !imageUrl.startsWith('data:image/')) {
      console.error('No valid image in AI response:', JSON.stringify(aiData));
      return errorResponse('No image generated by AI', 500, 'INTERNAL_ERROR');
    }

    // Parse base64 image
    const base64Match = imageUrl.match(/^data:image\/(\w+);base64,(.+)$/);
    if (!base64Match) {
      console.error('Invalid image format');
      return errorResponse('Invalid image format from AI', 500, 'INTERNAL_ERROR');
    }

    const imageType = base64Match[1]; // png, jpeg, webp
    const base64Data = base64Match[2];
    
    // Convert base64 to Uint8Array
    const binaryString = atob(base64Data);
    const bytes = new Uint8Array(binaryString.length);
    for (let i = 0; i < binaryString.length; i++) {
      bytes[i] = binaryString.charCodeAt(i);
    }

    // Create admin client for storage upload
    const supabaseAdmin = createClient(
      Deno.env.get('SUPABASE_URL')!,
      Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!
    );

    // Upload to storage
    const fileName = `${eventId}.${imageType}`;
    const contentType = `image/${imageType}`;
    
    const { error: uploadError } = await supabaseAdmin.storage
      .from('event-images')
      .upload(fileName, bytes, {
        contentType,
        upsert: true
      });

    if (uploadError) {
      console.error('Storage upload error:', uploadError);
      return errorResponse(`Failed to upload image: ${uploadError.message}`, 500, 'INTERNAL_ERROR');
    }

    // Get public URL
    const { data: urlData } = supabaseAdmin.storage
      .from('event-images')
      .getPublicUrl(fileName);

    const publicUrl = urlData.publicUrl;
    console.log(`Image uploaded successfully: ${publicUrl}`);

    return successResponse({
      imageUrl: publicUrl,
      eventId
    });

  } catch (error) {
    console.error('Error in admin-ai-image:', error);
    return errorResponse(
      error instanceof Error ? error.message : 'Unknown error',
      500,
      'INTERNAL_ERROR'
    );
  }
});
